# Site wide configuration

title: Howe Research Group
description: "Michael Howe Research Group at Iowa State University College of Business"
logo: bentley.gif # px default image used for Twitter summary card
teaser: 400x250.gif # px default teaser image used in image archive grid
locale: en_US
url: http://howe-lab.github.io
#url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Michael Howe
  email: 
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: "Assistant Professor, Iowa State University"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
